
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuinfdfrboxmawzfbtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aW5mZGZyYm94bWF3emZidGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTE3NTUsImV4cCI6MjA1NzQ4Nzc1NX0.5N4n-rqrOyL-Q2Y8Wal5UFxcz7Gru9z85unjQ_dzZfo";

// Create Supabase client with enhanced session persistence settings
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      storageKey: 'math-app-auth-token',
      storage: {
        getItem: (key) => {
          try {
            const itemStr = localStorage.getItem(key);
            if (!itemStr) return null;
            
            // Validate JSON format before parsing
            const item = JSON.parse(itemStr);
            
            // Check if session data is valid
            if (item && typeof item === 'object') {
              return item;
            }
            
            // If data is invalid, clean it up
            localStorage.removeItem(key);
            return null;
          } catch (error) {
            console.error('Error retrieving auth session:', error);
            // Clear corrupted session data
            localStorage.removeItem(key);
            return null;
          }
        },
        setItem: (key, value) => {
          try {
            localStorage.setItem(key, JSON.stringify(value));
          } catch (error) {
            console.error('Error storing auth session:', error);
          }
        },
        removeItem: (key) => {
          try {
            localStorage.removeItem(key);
          } catch (error) {
            console.error('Error removing auth session:', error);
          }
        }
      }
    }
  }
);
