
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuinfdfrboxmawzfbtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aW5mZGZyYm94bWF3emZidGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTE3NTUsImV4cCI6MjA1NzQ4Nzc1NX0.5N4n-rqrOyL-Q2Y8Wal5UFxcz7Gru9z85unjQ_dzZfo";

// Create Supabase client with enhanced session persistence settings
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'supabase.auth.token',
      storage: localStorage
    }
  }
);

// Check if we have an active session and log it
export const getSession = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error('Error getting session:', error);
      return null;
    }
    return data.session;
  } catch (err) {
    console.error('Unexpected error getting session:', err);
    return null;
  }
};
